/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asm.main;

import asm.lib.Library;

import java.util.Arrays;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;

public class App {
    public String getGreeting(Integer i) {
        return "Hello World! " + i;
    }

    public static void main(String[] args) throws ExecutionException, InterruptedException {
        Library library = new Library();;
        Arrays.stream(Library.class.getFields())
                .forEach((field) -> System.out.println(field.getName()));
        Future<String> future = library.calculateAsync();
        Integer i = 100;
        Boolean greet = library.someLibraryMethod();
        System.out.println(new App().getGreeting(i));
        System.out.println(greet);
        System.out.println(future.get());
    }
}
