/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asm.main;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class App {
    public String getGreeting(Integer i) {
        return "Hello World! " + i;
    }

    public static void main(String[] args) {
        MyClass myClass = new MyClass();
        Integer i = 100;
        Map<String, String> map = new HashMap<>();
        List<Integer> list = new ArrayList<>();
        list.add(i);
        map.put("Something", "Here");
        System.out.println(new App().getGreeting(list.get(0)));
        System.out.println(map.get("Something"));
    }
}
