/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package asm.main;

import asm.lib.Library;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;

public class App {
    public String getGreeting(Integer i) {
        return "Hello World! " + i;
    }

    public static void main(String[] args) throws ExecutionException, InterruptedException {
        Library library = new Library();
        //Future<String> future = library.calculateAsync();
        Integer i = 100;
        Boolean greet = library.someLibraryMethod();
        System.out.println(new App().getGreeting(i));
        System.out.println(greet.toString());
    }
}
